### ISSUE TITLE
Photos overwritten on account creation

### ISSUE THREAD

**Issue by bestouff** [GermainZ/Identiconizer#13]
Hi,

If you connect to your online address book using DAVdroid, when the contacts are first imported Identiconizer wrongly thinks the contacts don't have photos and creates identicons for them. There's some kind of race condition ensuing which results in some contacts having their original photos, and some having identicons. Some contact even have a small identicon but a big photo !

Maybe identiconizer should wait a bit when a contact is imported before deciding if it should create an icon ?

**Comment by GermainZ** [comment]
I've added a 5 seconds delay, which should fix this. Could you please try [this test build](https://forum.xda-developers.com/showpost.php?p=77636509&postcount=198) and let me know if it resolves the issue?
