### ISSUE TITLE
Release the current 1.4 (11) test build ?

### ISSUE THREAD

**Issue by breversa** [GermainZ/Identiconizer#15]
Hi,

Since the current 1.4 (11) test build (https://forum.xda-developers.com/showpost.php?p=77636509&postcount=198) has been successfully tested, what about an official release ? F-Droid could really use an update. :-)

**Comment by GermainZ** [comment]
I want to take care of #14 and this as soon as possible, I just haven't had enough time lately.

**Comment by IzzySoft** [comment]
For reference: [this issue](https://gitlab.com/fdroid/fdroiddata/issues/938) at F-Droid is waiting for this :wink:

**Comment by GermainZ** [comment]
I'll be able to take a look at this in 2 weeks. Thanks for the heads up :)

**Comment by GermainZ** [comment]
New build is up on F-Droid :) https://f-droid.org/packages/com.germainz.identiconizer/
