### ISSUE TITLE
Add favicon-based identicons

### ISSUE THREAD

**Issue by resotek** [GermainZ/Identiconizer#2]
Thank you for this useful App. Can you please consider adding favicons to the identiconizer? Favicons are easier to tell apart than identicons because they tend be more unique, and they're generally more relevant than an algorithmic identicon. 

For instance, 
- If the contact's email address is john@xposed.info, then download http://xposed.info/favicon.ico and use it as the photo. 
- If that favicon is not found, then search for favicons using the other email or website fields of that contact.
- If no favicons can be found, then generate a regular identicon.
- To ensure that several contacts using popular webmail addresses such as gmail or Yahoo don't end up with identical favicons, either (1) use the selected default identiconizer style, then add that domain's favicon in the lower right corner of that identicon, or (2) overlay the first character of their name over the favicon

For more flexibility, you could add a favicon-to-identicon threshold: if there are more than x contacts (e.g. 5) with the same favicon in the contact list, then combine the favicon with a single character overlay to distinguish them from each other. This will ensure that contact photos using common email addresses such as gmail or Yahoo don't look identical.

**Comment by GermainZ** [comment]
(Sorry for the late reply, but I'm going through the issues now after a long break from identiconizer.)

Unfortunately, favicons are usually of extremely low resolution compared to what would look good for a contact's photo (usually less than Identiconizer's lowest setting, 96x96, which is also becoming quite small on modern smartphone resolutions).

Pull requests would be welcome, and I might even look into it if there's interest, but it seems like a fair amount of work for a suboptimal feature.
